FROM opencpu/rstudio

RUN apt-get update && apt-get install -y \
    libcurl4-openssl-dev \
    libssl-dev \
    libxml2-dev

# https://askubuntu.com/questions/921207/installing-package-containing-glib-h
RUN dpkg -r --force-all libglib2.0-0 && \
    apt install -f -y && \
    apt install libglib2.0-0 -y && \
    apt install libglib2.0-dev -y

RUN apt-get install libcairo2-dev libxt-dev -y

RUN R -e 'install.packages("XML");' && \
    R -e 'install.packages("plotly");' && \
    R -e 'install.packages("BiocManager");' && \
    R -e 'BiocManager::install("genefilter", version = "3.9")' && \
    R -e 'BiocManager::install("GlobalAncova", version = "3.9")' && \
    R -e 'BiocManager::install("impute", version = "3.9")' && \
    R -e 'BiocManager::install("KEGGgraph", version = "3.9")' && \
    R -e 'BiocManager::install("limma", version = "3.9")' && \
    R -e 'BiocManager::install("pcaMethods", version = "3.9")' && \
    R -e 'BiocManager::install("preprocessCore", version = "3.9")' && \
    R -e 'BiocManager::install("Rgraphviz", version = "3.9")' && \
    R -e 'BiocManager::install("siggenes", version = "3.9")' && \
    R -e 'BiocManager::install("SSPA", version = "3.9")' && \
    R -e 'BiocManager::install("sva", version = "3.9")'

RUN R -e 'install.packages("devtools"); library(devtools)'
RUN R -e 'library(devtools); devtools::install_github("klutometis/roxygen")'
RUN R -e 'BiocManager::install("impute", version = "3.9")'
RUN R -e 'install.packages("missForest")'
RUN R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/mnormt/mnormt_1.5-6.tar.gz", repos=NULL, type="source")'

ADD viime /viime
RUN R -e 'setwd("/viime"); devtools::update_packages(devtools::dev_package_deps()$package, dependencies=NA, upgrade="never");' && rm -fr /viime
