# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"

  config.vm.network "forwarded_port", guest: 80, host:8000
  config.vm.network "forwarded_port", guest: 443, host:8001
  
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", 4096]
    vb.customize ["modifyvm", :id, "--cpus", 2]
  end

  config.vm.provision "ansible" do |ansible|
    ansible.galaxy_role_file = "ansible/requirements.yml"
    ansible.playbook = "ansible/site.yml"
    ansible.extra_vars = {
      metabulo_sdist_path: '../../dist/metabulo-0.1.0.tar.gz',
      flask_secret: 'thisisasecretbetweenyouandme',
      aws_access_key_id: 'aws_access_key_id',
      aws_secret_access_key: 'aws_secret_access_key'
    }
  end

end
