"""
empty message

Revision ID: 09cced627ac9
Revises: 543488f52e75
Create Date: 2019-09-24 09:57:01.115728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09cced627ac9'
down_revision = '543488f52e75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('csv_file', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('csv_file', 'description')
    # ### end Alembic commands ###
