"""
Introduce normalization_argument

Revision ID: 44b9d38a1bb9
Revises:
Create Date: 2019-08-20 13:50:38.472393
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44b9d38a1bb9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('csv_file', sa.Column('normalization_argument', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('csv_file', 'normalization_argument')
    # ### end Alembic commands ###
