"""
empty message

Revision ID: 48a6ac284a99
Revises: ea2f36eda0d8
Create Date: 2019-10-31 13:02:45.551325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48a6ac284a99'
down_revision = 'ea2f36eda0d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('csv_file', sa.Column('sample_group', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('csv_file', 'sample_group')
    # ### end Alembic commands ###
