"""
empty message

Revision ID: 55365e50ff52
Revises: e8525e7201b6
Create Date: 2019-11-14 09:36:32.454460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55365e50ff52'
down_revision = 'e8525e7201b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample_group', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample_group', 'order')
    # ### end Alembic commands ###
