"""
empty message

Revision ID: 92846651ae9d
Revises: a8a254f68f5e
Create Date: 2019-10-07 10:49:57.511927

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '92846651ae9d'
down_revision = 'a8a254f68f5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_level',
    sa.Column('csv_file_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['csv_file_id'], ['csv_file.id'], name=op.f('fk_group_level_csv_file_id_csv_file')),
    sa.PrimaryKeyConstraint('csv_file_id', 'name', name=op.f('pk_group_level'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_level')
    # ### end Alembic commands ###
