"""
empty message

Revision ID: e6f315c1f2f6
Revises: 92846651ae9d
Create Date: 2019-10-24 16:26:30.560845

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'e6f315c1f2f6'
down_revision = '92846651ae9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('validated_metabolite_table', sa.Column('imputation_info', sqlalchemy_utils.types.json.JSONType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('validated_metabolite_table', 'imputation_info')
    # ### end Alembic commands ###
