"""
empty message

Revision ID: e8525e7201b6
Revises: 48a6ac284a99
Create Date: 2019-11-12 08:41:14.935767

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'e8525e7201b6'
down_revision = '48a6ac284a99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sample_group',
      sa.Column('name', sa.String(), nullable=False),
      sa.Column('description', sa.String(), nullable=True),
      sa.PrimaryKeyConstraint('name', name=op.f('pk_sample_group'))
    )

    # note no foreign key constraint due to limitation of SQLite
    # create table for each entry
    op.execute('INSERT INTO sample_group(name) SELECT distinct sample_group as name FROM csv_file WHERE sample_group is not null;')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sample_group')
    # ### end Alembic commands ###
