"""
empty message

Revision ID: ea2f36eda0d8
Revises: e6f315c1f2f6
Create Date: 2019-10-29 16:40:32.673305

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'ea2f36eda0d8'
down_revision = 'e6f315c1f2f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table_column', sa.Column('meta', sqlalchemy_utils.types.json.JSONType(), nullable=True))
    op.add_column('table_column', sa.Column('subtype', sa.String(), nullable=True))
    op.add_column('table_row', sa.Column('meta', sqlalchemy_utils.types.json.JSONType(), nullable=True))
    op.add_column('table_row', sa.Column('subtype', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table_row', 'subtype')
    op.drop_column('table_row', 'meta')
    op.drop_column('table_column', 'subtype')
    op.drop_column('table_column', 'meta')
    # ### end Alembic commands ###
